# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: pt

pipeline:
# No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# If you'd like to customize it, uncomment and adjust the pipeline.
# See https://rasa.com/docs/rasa/tuning-your-model for more information.
  - name: SpacyNLP
    model: pt_core_news_lg
    case_sensitive: False
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
    case_sensitive: false
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: word
    lowercase: true
    strip_accents: unicode
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    lowercase: true
    max_ngram: 4
    min_ngram: 1
    strip_accents: unicode
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: FallbackClassifier
    ambiguity_threshold: 0.1
    threshold: 0.8

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# No configuration for policies was provided. The following default policies were used to train your model.
# If you'd like to customize them, uncomment and adjust the policies.
# See https://rasa.com/docs/rasa/policies for more information.
  - name: TEDPolicy
    max_history: 4
    epochs: 200
    constrain_similarities: true
  - name: UnexpecTEDIntentPolicy
    epochs: 250
    max_history: 3
    tolerance: 0
    ignore_intents_list: [saudar, noticia, start, rastreio_notificacao, ajuda, valor_ativo, menu, gerenciar_notificacao, rastrear_ativos, remover_ativos, adicionar_ativos]
  - name: RulePolicy
    core_fallback_action_name: action_custom_fallback
    core_fallback_threshold: 0.8
    enable_fallback_prediction: true
  - name: AugmentedMemoizationPolicy
    max_history: 3
